services:
  mongodb:
    image: mongo:8.0.13-noble
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  mongodb_data: