services:
  mongodb:
    image: mongo:8.0.13-noble
    container_name: mongodb
    ports:
      - "27007:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${RAG_MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${RAG_MONGODB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  mongodb_data:
