services:
  pgvector:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${RAG_POSTGRES_DB}
      - POSTGRES_USER=${RAG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${RAG_POSTGRES_PASSWORD}
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  pgvector_data:
