name: Code Quality Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install black isort flake8 mypy
    - name: Run Black
      run: black --check .
    - name: Run isort
      run: isort --check-only . --profile black
    - name: Run Flake8
      run: flake8 . --max-line-length=100 --per-file-ignores="__init__.py:F401" --extend-ignore E203
    - name: Run mypy
      run: mypy --ignore-missing-imports --install-types --non-interactive .
